### PR TITLE
Downloads: Add packages for 1.12.0-beta.1

### PR DESCRIPTION
**Pull request by jzaefferer**
Updates download.jqueryui.com module to fix create-quickdownload task.

Running `grunt deploy` (with verbose flag) locally fails with an apparently unrelated issue:

```
Publishing demos-highlight/accordion/collapsible.html...
Warning: XML-RPC fault: Invalid file type Use --force to continue.
```

### CODE REVIEW

**Comment by scottgonzalez** [comment]
Looks good.

The XML-RPC error is surprising. You can try to work around it by adding to [the mime types list](https://github.com/jquery/jquery-wp-content/blob/613a155bee9659fc6162216ed5838a79395d6f85/mu-plugins/jquery-filters.php#L34-L43) but I don't know why you'd suddenly be having this problem.

**Comment by jzaefferer** [comment]
That fixes it. Not sure where the issue is coming from. This Vagrant-provided WordPress is on 3.8.1.

This can go live, right?

**Comment by scottgonzalez** [comment]
> That fixes it. Not sure where the issue is coming from.

Me neither.

> This Vagrant-provided WordPress is on 3.8.1.

There's a PR to fix this, but I haven't gotten around to reviewing it yet. https://github.com/jquery/jquery-wp-content/pull/385

> This can go live, right?

Yup :-)

**Comment by jzaefferer** [comment]
Tagged as v1.11.24.

**Pull request merged**
