### PR TITLE
Gruntfile.js indented properly

### PR DESCRIPTION
**Pull request by ashg1910**

### CODE REVIEW

**Comment by arthurvr** [comment]
From http://contribute.jquery.org/style-guide/js/#full-file-closures:

```js
module.exports = function( grunt ) {
 
// This doesn't get indented
 
};
```

Also, we use tabs, no spaces.

**Comment by ashg1910** [comment]
@arthurvr I indented this so that it is easy to rea

**Comment by arthurvr** [comment]
@ashg1910 It being easier to read is at the end just a personal opinion. This is how our style guide states it, and that's where the whole team agrees on.

> When an entire file is wrapped in a closure, the body of the closure is not indented.

**Comment by ashg1910** [comment]
okay :)
And what is the tabspace you use?
8 or 4?

**Comment by arthurvr** [comment]
> And what is the tabspace you use?
8 or 4?

That does not make sense, we use 'real' tabs, no spaces :)

**Comment by arschmitz** [comment]
@arthurvr this actually does matter because it effects our max line length rules. We use real tabs but count them as 4 space.

**Pull request closed without merging**
